workflows:
  flutter-android:
    name: Nova Android Build
    max_build_duration: 20
    environment:
      flutter: stable
      vars:
        BUILD_NAME: "0.9.0"
        BUILD_NUMBER: "1"
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release --build-name=$BUILD_NAME --build-number=$BUILD_NUMBER
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your.email@example.com