name: nova
description: An AI assistant app like Jarvis named Nova.
publish_to: 'none'
version: 0.9.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true