name: nova
description: A smart AI assistant like Jarvis
version: 0.9.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  speech_to_text: ^5.9.0
  flutter_tts: ^3.5.2
  url_launcher: ^6.1.7
  permission_handler: ^10.2.0
  http: ^0.13.5
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

