name: nova_ai_assistant
description: An AI assistant app with voice control and smart automation
version: 0.9.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.0
  provider: ^6.0.5
  http: ^0.13.6
  url_launcher: ^6.1.10
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.0
  flutter_local_notifications: ^15.1.0
  device_info_plus: ^9.0.3
  android_intent_plus: ^4.0.3
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
    - assets/images/
